
    create table if not exists public.categories (
       id int8 generated by default as identity,
        name varchar(200),
        primary key (id),
       constraint UK_t8o6pivur7nn124jehx7cygw5 unique (name)
    );

    create table if not exists public.compilations (
       id int8 generated by default as identity,
        pinned boolean,
        title varchar(200),
        primary key (id)
    );

    create table if not exists public.users (
        id int8 generated by default as identity,
        email varchar(200),
        name varchar(200),
        primary key (id),
        constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
    );

    create table if not exists public.events (
       id int8 generated by default as identity,
        annotation varchar(1200),
        created_on timestamp,
        description varchar(1200),
        event_date timestamp,
        location varchar(255),
        paid boolean,
        participant_limit int4,
        published_on timestamp,
        request_moderation boolean,
        state varchar(255),
        title varchar(200),
        category_id int8,
        user_id int8,
        primary key (id),
           constraint FKo6mla8j1p5bokt4dxrlmgwc28
           foreign key (category_id)
           references public.categories,

           constraint FKat8p3s7yjcp57lny4udqvqncq
            foreign key (user_id)
                references public.users
    );

    create table if not exists public.requests (
       id int8 generated by default as identity,
        created timestamp,
        status varchar(255),
        event_id int8,
        requester_id int8,
        primary key (id),
       constraint ComplexKeyConstraint unique (event_id, requester_id),
           constraint FKm7vtr0204t3xcymbx4sa9t1ot
           foreign key (event_id)
           references public.events,

            constraint FKeoax2t4j9i61p9lmon3009tr4
            foreign key (requester_id)
                references public.users
    );






    create table if not exists event_compilation (
       event_id int8 not null,
        compilation_id int8 not null,
           constraint FKcjjymedxn01uxg7g6tk0a4xwg
           foreign key (compilation_id)
           references public.compilations,

            constraint FKe819nswbe795oqkfyv8r4xhok
            foreign key (event_id)
                references public.events
    );
