version: '3.1'
services:
  stats-client:
    build: stats-parent/stats-client
    image: stats-client
    container_name: stats-client-container
    ports:
      - "9090:9090"
    restart: on-failure
    depends_on:
      - stats-db
    environment:
      - EXPLORE_WITH_ME_SERVER_URL=http://stats-server:8888

  stats-server:
    build: stats-parent/stats-server
    image: stats-server
    container_name: stats-server-container
    ports:
      - "8888:8888"
    restart: on-failure
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:14.6-alpine
    container_name: postgres_db
    ports:
      - "6541:5432"
#    volumes:
#      - /data/postgresql/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#  ewm-service:
#    ports:
#      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine
