version: '3.1'
services:
  stats-gateway:
    build: stats-parent/gateway
    image: stats-gateway
    container_name: stats-client-container
    ports:
      - "9090:9090"
    restart: on-failure
    depends_on:
      - stats-db
    environment:
      - EXPLORE_WITH_ME_SERVER_URL=http://stats-server:8888

  stats-server:
    build: stats-parent/stats-server
    image: stats-server
    container_name: stats-server-container
    ports:
      - "8888:8888"
    restart: on-failure
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:14.6-alpine
    container_name: postgres-db
    ports:
      - "6541:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ewm-service
    image: main-tesis
    container_name: main-container
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - ewm-db
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5433/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - EXPLORE_WITH_ME_SERVER_URL=http://stats-server:8888

  ewm-db:
    image: postgres:14.6-alpine
    container_name: main-postgres-db
    ports:
      - "6891:5433"
    command: -p 5433
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
