CREATE TABLE IF NOT EXISTS statistics
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uri        VARCHAR(400)                            NOT NULL,
    ip         VARCHAR(400)                            NOT NULL,
    app        VARCHAR(400)                            NOT NULL,
    time_stamp timestamp,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);